countries = {
    "China": {"capital": "Beijing", "population": 1439323776, "wiki": "China (Chinese: 中国; pinyin: Zhōngguó), officially the People's Republic of China (PRC; Chinese: 中华人民共和国; pinyin: Zhōnghuá Rénmín Gònghéguó), is a country in East Asia. It is the world's most populous country, with a population of more than 1.4 billion people."},
    "India": {"capital": "New Delhi", "population": 1380004385, "wiki": "India, officially the Republic of India (Hindi: Bhārat Gaṇarājya), is a country in South Asia. It is the seventh-largest country by area, the second-most populous country, and the most populous democracy in the world."},
    "USA": {"capital": "Washington, D.C.", "population": 331002651, "wiki": "The United States of America (U.S.A. or USA), commonly known as the United States (U.S. or US) or America, is a transcontinental country primarily located in North America. It consists of 50 states, a federal district, five major unincorporated territories, nine minor outlying islands, and 326 Indian reservations with limited sovereignty."},
    "Japan": {"capital": "Tokyo", "population": 126476461, "wiki": "Japan (Japanese: 日本, Nippon or Nihon, and formally 日本国, Nihonkoku) is an island country in East Asia. It is situated in the northwest Pacific Ocean, and is bordered on the west by the Sea of Japan, while extending from the Sea of Okhotsk in the north toward the East China Sea, Philippine Sea, and Taiwan in the south."},
    "South Korea": {"capital": "Seoul", "population": 51815810, "wiki": "South Korea, officially the Republic of Korea (ROK), is a country in East Asia, constituting the southern part of the Korean Peninsula and sharing a land border with North Korea. Its western border is formed by the Yellow Sea, while its eastern border is defined by the Sea of Japan."},
    "Mexico" : {"capital": "Mexico City", "population": 131832888, "wiki": "Mexico, officially the United Mexican States, is a country in the southern portion of North America. It is bordered to the north by the United States; to the south and west by the Pacific Ocean; to the southeast by Guatemala, Belize, and the Caribbean Sea; and to the east by the Gulf of Mexico."},
    "France" : {"capital": "Paris", "population": 64626628, "wiki": "France (French: fʁɑ̃s), officially the French Republic (French: République française), is a transcontinental country predominantly located in Western Europe and spanning overseas regions and territories in the Americas and the Atlantic, Pacific and Indian Oceans."},
    "Vietnam" : {"capital": "Hanoi", "population": 98186856, "wiki": "Vietnam (Vietnamese: Việt Nam, vîət nāːm), officially the Socialist Republic of Vietnam, is a country in Southeast Asia, at the eastern edge of mainland Southeast Asia, with an area of 311,699 square kilometres (120,348 sq mi) and population of 96 million, making it the world's fifteenth-most populous country."},
    "Taiwan" : {"capital": "Taipei", "population": 23893394, "wiki": "Taiwan, officially the Republic of China (ROC), is a country in East Asia, at the junction of the East and South China Seas in the northwestern Pacific Ocean, with the People's Republic of China (PRC) to the northwest, Japan to the northeast, and the Philippines to the south."},
    "Australia" : {"capital": "Canberra", "population": 26177413, "wiki": "Australia, officially the Commonwealth of Australia, is a sovereign country comprising the mainland of the Australian continent, the island of Tasmania, and numerous smaller islands. With an area of 7,617,930 square kilometres (2,941,300 sq mi), Australia is the largest country by area in Oceania and the world's sixth-largest country."}
}